github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/redgifs-downloader",
  "https://serp.co/products/redgifs-downloader/reviews/",
  "https://extensions.serp.co/redgifs-downloader",
  "https://browserextensions.io/redgifs-downloader"
]
